// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xckwugeyjjeppvapfvnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhja3d1Z2V5amplcHB2YXBmdm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzAyODcsImV4cCI6MjA2MjgwNjI4N30.XIfc8hQGr8iVYA5cxvdlUASyST7nfQSFpe2-8vKHKWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);